
GuildSheetData = {
["lastExportTime"] = 1783027924,
["guildName"] = "Evolve",
["ignoreRanks"] = {
["social"] = true,
},
["members"] = {
{
["note"] = "Aenia",
["name"] = "Aenia",
["rankIndex"] = 0,
["class"] = "SHAMAN",
["rank"] = "Officer",
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Chûbbycheeks",
["rankIndex"] = 2,
["class"] = "PRIEST",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Aeniathree",
["rankIndex"] = 2,
["class"] = "SHAMAN",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Heyadorable",
["rankIndex"] = 2,
["class"] = "WARLOCK",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Tyforurtime",
["rankIndex"] = 2,
["class"] = "DEMONHUNTER",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Arkae",
["name"] = "Arkaex",
["rankIndex"] = 5,
["class"] = "MAGE",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Arkae",
["name"] = "Arkae",
["rankIndex"] = 4,
["class"] = "MAGE",
["rank"] = "Trial Raider",
["realm"] = "Draenor",
},
{
["note"] = "Arkae",
["name"] = "Arkaae",
["rankIndex"] = 5,
["class"] = "MAGE",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Arkae",
["name"] = "Arkaesofty",
["rankIndex"] = 5,
["class"] = "MAGE",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Arkae",
["name"] = "Arkaee",
["rankIndex"] = 5,
["class"] = "MAGE",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Ayije",
["name"] = "Ayije",
["rankIndex"] = 5,
["class"] = "PRIEST",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Ayije",
["name"] = "Hotdogsuzy",
["rankIndex"] = 3,
["class"] = "DRUID",
["rank"] = "Raider",
["realm"] = "TwistingNether",
},
{
["note"] = "Ayije",
["name"] = "Ayijexo",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Ayije",
["name"] = "Uwurawr",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Ayije",
["name"] = "Ayijeqtx",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Belle",
["name"] = "Belledk",
["rankIndex"] = 4,
["class"] = "DEATHKNIGHT",
["rank"] = "Trial Raider",
["realm"] = "Draenor",
},
{
["note"] = "Belle",
["name"] = "Bellethanos",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "SteamwheedleCartel",
},
{
["note"] = "Belle",
["name"] = "Bellemeow",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "BronzeDragonflight",
},
{
["note"] = "Belle",
["name"] = "Bellenya",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Belle",
["name"] = "Bellerunner",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Ravencrest",
},
{
["note"] = "Bigt",
["name"] = "Bigtilted",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Bigt",
["name"] = "Bigtaunt",
["rankIndex"] = 5,
["class"] = "WARRIOR",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Bigt",
["name"] = "Bigtrunk",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Bigt",
["name"] = "Bigtilter",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Bigt",
["name"] = "Bigchai",
["rankIndex"] = 3,
["class"] = "MONK",
["rank"] = "Raider",
["realm"] = "Draenor",
},
{
["note"] = "Bigt",
["name"] = "Bigtje",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Chapper",
["name"] = "Snowmixyfan",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Chapper",
["name"] = "Chapperr",
["rankIndex"] = 3,
["class"] = "WARRIOR",
["rank"] = "Raider",
["realm"] = "TwistingNether",
},
{
["note"] = "Chapper",
["name"] = "Netanyahufan",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Chapper",
["name"] = "Latinaenjoyr",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Chapper",
["name"] = "Chappertwo",
["rankIndex"] = 5,
["class"] = "WARRIOR",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Chapper",
["name"] = "Buffmasteryi",
["rankIndex"] = 5,
["class"] = "WARRIOR",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Dalote",
["name"] = "Dalotee",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Dalote",
["name"] = "Dalote",
["rankIndex"] = 4,
["class"] = "WARLOCK",
["rank"] = "Trial Raider",
["realm"] = "Draenor",
},
{
["note"] = "Dalote",
["name"] = "Daloteh",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Dolanz",
["name"] = "Dolanz",
["rankIndex"] = 3,
["class"] = "DEMONHUNTER",
["rank"] = "Raider",
["realm"] = "TarrenMill",
},
{
["note"] = "Dolanz",
["name"] = "Dolandh",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Dolanz",
["name"] = "Dolzi",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Dolanz",
["name"] = "Dolans",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Dsune",
["name"] = "Twosune",
["rankIndex"] = 2,
["class"] = "DRUID",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Dsune",
["name"] = "Threesune",
["rankIndex"] = 2,
["class"] = "DRUID",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Dsune",
["name"] = "Dsune",
["rankIndex"] = 1,
["class"] = "DRUID",
["rank"] = "Officer",
["realm"] = "Draenor",
},
{
["note"] = "Dsune",
["name"] = "Fivesune",
["rankIndex"] = 2,
["class"] = "DRUID",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Fahl",
["name"] = "Fahlcx",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Fahl",
["name"] = "Fahlxd",
["rankIndex"] = 5,
["class"] = "PRIEST",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Fahl",
["name"] = "Fahlxp",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Fahl",
["name"] = "Fahlxc",
["rankIndex"] = 4,
["class"] = "EVOKER",
["rank"] = "Trial Raider",
["realm"] = "TarrenMill",
},
{
["note"] = "Flay",
["name"] = "Flaylock",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Flay",
["name"] = "Flay",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "Medivh",
},
{
["note"] = "Flay",
["name"] = "Flayhunter",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Flay",
["name"] = "Flaydk",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Flay",
["name"] = "Flayvoker",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Flay",
["name"] = "Flaypala",
["rankIndex"] = 3,
["class"] = "PALADIN",
["rank"] = "Raider",
["realm"] = "Kazzak",
},
{
["note"] = "Flay",
["name"] = "Flaef",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "DarkmoonFaire",
},
{
["note"] = "Flay",
["name"] = "Flaypalatwo",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "Kazzak",
},
{
["note"] = "Flay",
["name"] = "Flaywar",
["rankIndex"] = 5,
["class"] = "WARRIOR",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Flay",
["name"] = "Cutewoman",
["rankIndex"] = 5,
["class"] = "PRIEST",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Garohunt",
["rankIndex"] = 3,
["class"] = "HUNTER",
["rank"] = "Raider",
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Shacow",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "BurningLegion",
},
{
["note"] = "Garo",
["name"] = "Garodh",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Kurwadru",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Kurwahunt",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Garolock",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Krakon",
["name"] = "Khromå",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Krakon",
["name"] = "Deåth",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Turalyon",
},
{
["note"] = "Krakon",
["name"] = "Dhrogon",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Krakon",
["name"] = "Krakón",
["rankIndex"] = 4,
["class"] = "SHAMAN",
["rank"] = "Trial Raider",
["realm"] = "TarrenMill",
},
{
["note"] = "Mada",
["name"] = "Baldmidget",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Mada",
["name"] = "Yùümïkîttën",
["rankIndex"] = 4,
["class"] = "DEMONHUNTER",
["rank"] = "Trial Raider",
["realm"] = "TwistingNether",
},
{
["note"] = "Mada",
["name"] = "Wearesoback",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Mirage",
["name"] = "Miragetwo",
["rankIndex"] = 2,
["class"] = "ROGUE",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragedruid",
["rankIndex"] = 2,
["class"] = "DRUID",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragedk",
["rankIndex"] = 2,
["class"] = "DEATHKNIGHT",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragedh",
["rankIndex"] = 2,
["class"] = "DEMONHUNTER",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Mìrage",
["rankIndex"] = 1,
["class"] = "ROGUE",
["rank"] = "Officer",
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragethree",
["rankIndex"] = 2,
["class"] = "ROGUE",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Mistu",
["name"] = "Mistujuhu",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "BurningLegion",
},
{
["note"] = "Mistu",
["name"] = "Misturawr",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "BurningLegion",
},
{
["note"] = "Mistu",
["name"] = "Mistubrew",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "BurningLegion",
},
{
["note"] = "Mistu",
["name"] = "Mistudk",
["rankIndex"] = 4,
["class"] = "DEATHKNIGHT",
["rank"] = "Trial Raider",
["realm"] = "BurningLegion",
},
{
["note"] = "Nish",
["name"] = "Nishdemon",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Nish",
["name"] = "Nishdr",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Nish",
["name"] = "Nishaman",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Nish",
["name"] = "Nishevoker",
["rankIndex"] = 3,
["class"] = "EVOKER",
["rank"] = "Raider",
["realm"] = "Draenor",
},
{
["note"] = "Panda",
["name"] = "Pandamw",
["rankIndex"] = 3,
["class"] = "MONK",
["rank"] = "Raider",
["realm"] = "TwistingNether",
},
{
["note"] = "Panda",
["name"] = "Pandevoker",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Panda",
["name"] = "Femboycheeks",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Panda",
["name"] = "Panladin",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Panda",
["name"] = "Pandadru",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Panda",
["name"] = "Pandapi",
["rankIndex"] = 5,
["class"] = "PRIEST",
["rank"] = "Raider Alt",
["realm"] = "TarrenMill",
},
{
["note"] = "Panda",
["name"] = "Pandaclanker",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Peluche",
["name"] = "Ugotconvoked",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "Archimonde",
},
{
["note"] = "Peluche",
["name"] = "Peluchevoker",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "Ysondre",
},
{
["note"] = "Peluche",
["name"] = "Pititpeluche",
["rankIndex"] = 4,
["class"] = "PRIEST",
["rank"] = "Trial Raider",
["realm"] = "Ysondre",
},
{
["note"] = "Pricey",
["name"] = "Priceybomba",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Pricey",
["name"] = "Priceydwnbad",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "DieAldor",
},
{
["note"] = "Pricey",
["name"] = "Priceyhiphop",
["rankIndex"] = 5,
["class"] = "PRIEST",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Pricey",
["name"] = "Príceyy",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Pricey",
["name"] = "Prîceyy",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Pricey",
["name"] = "Priceywaters",
["rankIndex"] = 3,
["class"] = "MAGE",
["rank"] = "Raider",
["realm"] = "TwistingNether",
},
{
["note"] = "Pricey",
["name"] = "Pricéyybeam",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "Medivh",
},
{
["note"] = "Pricey",
["name"] = "Priceyyremix",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "DieAldor",
},
{
["note"] = "Pricey",
["name"] = "Priceyythree",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Replair",
["name"] = "Replairpr",
["rankIndex"] = 3,
["class"] = "PRIEST",
["rank"] = "Raider",
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairwl",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairbust",
["rankIndex"] = 5,
["class"] = "MAGE",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairxd",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replair",
["rankIndex"] = 5,
["class"] = "DEMONHUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairboom",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairdk",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replaire",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Sanky",
["name"] = "Sankp",
["rankIndex"] = 2,
["class"] = "PRIEST",
["rank"] = "Officer Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Sanky",
["name"] = "Sanksinatra",
["rankIndex"] = 1,
["class"] = "MAGE",
["rank"] = "Officer",
["realm"] = "TwistingNether",
},
{
["note"] = "Sanky",
["name"] = "Sankyboyle",
["rankIndex"] = 2,
["class"] = "DEATHKNIGHT",
["rank"] = "Officer Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Sanky",
["name"] = "Slamky",
["rankIndex"] = 2,
["class"] = "WARRIOR",
["rank"] = "Officer Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Sanky",
["name"] = "Sankdug",
["rankIndex"] = 2,
["class"] = "DRUID",
["rank"] = "Officer Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Sanky",
["name"] = "Sankys",
["rankIndex"] = 2,
["class"] = "MONK",
["rank"] = "Officer Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Sanky",
["name"] = "Sanklampard",
["rankIndex"] = 2,
["class"] = "MAGE",
["rank"] = "Officer Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Shai",
["name"] = "Bigdicklinus",
["rankIndex"] = 5,
["class"] = "WARRIOR",
["rank"] = "Raider Alt",
["realm"] = "Silvermoon",
},
{
["note"] = "Shai",
["name"] = "Shaihuloot",
["rankIndex"] = 4,
["class"] = "WARRIOR",
["rank"] = "Trial Raider",
["realm"] = "Silvermoon",
},
{
["note"] = "Shai",
["name"] = "Shaimindut",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Silvermoon",
},
{
["note"] = "Varas",
["name"] = "Folyr",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Unlovedvaras",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Ipetmypet",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Varasdruid",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Váras",
["rankIndex"] = 3,
["class"] = "ROGUE",
["rank"] = "Raider",
["realm"] = "Draenor",
},
{
["note"] = "Worst",
["name"] = "Worstxddkk",
["rankIndex"] = 5,
["class"] = "DEATHKNIGHT",
["rank"] = "Raider Alt",
["realm"] = "Moonglade",
},
{
["note"] = "Worst",
["name"] = "Worstxp",
["rankIndex"] = 5,
["class"] = "ROGUE",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Worst",
["name"] = "Worstwalker",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Worst",
["name"] = "Iambad",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Worst",
["name"] = "Worstsshadow",
["rankIndex"] = 5,
["class"] = "PRIEST",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Worst",
["name"] = "Worstxpal",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "TwistingNether",
},
{
["note"] = "Worst",
["name"] = "Worstanimal",
["rankIndex"] = 5,
["class"] = "DRUID",
["rank"] = "Raider Alt",
["realm"] = "Ravencrest",
},
{
["note"] = "Worst",
["name"] = "Xddshock",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "Ravencrest",
},
{
["note"] = "Worst",
["name"] = "Worstxdd",
["rankIndex"] = 4,
["class"] = "DEATHKNIGHT",
["rank"] = "Trial Raider",
["realm"] = "TwistingNether",
},
{
["note"] = "Wort",
["name"] = "Garfxd",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Fatfckinchud",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Whort",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Ftpg",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Dogmaxxing",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Whortxd",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Wortxd",
["rankIndex"] = 3,
["class"] = "HUNTER",
["rank"] = "Raider",
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Dogmaxxer",
["rankIndex"] = 5,
["class"] = "HUNTER",
["rank"] = "Raider Alt",
["realm"] = "Agamaggan",
},
{
["note"] = "Zara",
["name"] = "Zazafour",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zaraines",
["rankIndex"] = 2,
["class"] = "SHAMAN",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazaseven",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazathree",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Turbogrief",
["rankIndex"] = 5,
["class"] = "EVOKER",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarastwo",
["rankIndex"] = 5,
["class"] = "SHAMAN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarainew",
["rankIndex"] = 5,
["class"] = "WARRIOR",
["rank"] = "Raider Alt",
["realm"] = "Kazzak",
},
{
["note"] = "Zara",
["name"] = "Thisshtgasaf",
["rankIndex"] = 5,
["class"] = "MONK",
["rank"] = "Raider Alt",
["realm"] = "Dethecus",
},
{
["note"] = "Zara",
["name"] = "Zaraine",
["rankIndex"] = 1,
["class"] = "PALADIN",
["rank"] = "Officer",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Buffpaladins",
["rankIndex"] = 2,
["class"] = "MONK",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarainep",
["rankIndex"] = 5,
["class"] = "PALADIN",
["rank"] = "Raider Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Nerfmønks",
["rankIndex"] = 2,
["class"] = "MONK",
["rank"] = "Officer Alt",
["realm"] = "Draenor",
},
{
["note"] = "Zovac",
["name"] = "Zovacfour",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Ragnaros",
},
{
["note"] = "Zovac",
["name"] = "Zovactwo",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Ragnaros",
},
{
["note"] = "Zovac",
["name"] = "Zovac",
["rankIndex"] = 3,
["class"] = "WARLOCK",
["rank"] = "Raider",
["realm"] = "TwistingNether",
},
{
["note"] = "Zovac",
["name"] = "Zovacthree",
["rankIndex"] = 5,
["class"] = "WARLOCK",
["rank"] = "Raider Alt",
["realm"] = "Ragnaros",
},
},
["ignoreMembers"] = {
["keffalo"] = true,
},
}
