
GuildSheetData = {
["lastExportTime"] = 1742048710,
["ignoreRanks"] = {
},
["members"] = {
{
["note"] = "",
["name"] = "Pittaloaf",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Vízquél",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Vízquèl",
["rank"] = "Social",
["class"] = "WARLOCK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Vizshammy",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Vellhar",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Yòkér",
["rank"] = "Social",
["class"] = "HUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Relaxedd",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Outland",
},
{
["note"] = "",
["name"] = "Jòker",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Goodguybob",
["rank"] = "Social",
["class"] = "PALADIN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Foundbrownie",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Lightloaf",
["rank"] = "Social",
["class"] = "PALADIN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Madamex",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Lóstbrównie",
["rank"] = "Social",
["class"] = "WARRIOR",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Lillxa",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Fluqzie",
["rank"] = "Social",
["class"] = "ROGUE",
["rankIndex"] = 6,
["realm"] = "Stormscale",
},
{
["note"] = "",
["name"] = "Sanfire",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Rosci",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Mikorrà",
["rank"] = "Social",
["class"] = "WARLOCK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Supergremlin",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Blackrock",
},
{
["note"] = "",
["name"] = "Margebrew",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "",
["name"] = "Fluqzxd",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "50/50 best of both",
["name"] = "Hovisloaf",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Aenia",
["rank"] = "Officer",
["class"] = "SHAMAN",
["rankIndex"] = 0,
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Aeniathree",
["rank"] = "Officer Alt",
["class"] = "SHAMAN",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Heyadorable",
["rank"] = "Officer Alt",
["class"] = "WARLOCK",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Aénia",
["rank"] = "Officer Alt",
["class"] = "SHAMAN",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Aenia",
["name"] = "Áenia",
["rank"] = "Officer Alt",
["class"] = "PALADIN",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Aenìa",
["name"] = "Aeniá",
["rank"] = "Officer Alt",
["class"] = "ROGUE",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthgate",
["rank"] = "Raider Alt",
["class"] = "WARLOCK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthmagus",
["rank"] = "Raider Alt",
["class"] = "MAGE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthshaman",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthypie",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthdemon",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthbench",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthwings",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthwar",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Arth",
["name"] = "Arthvoker",
["rank"] = "Raider",
["class"] = "EVOKER",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Ayije",
["name"] = "Ayije",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "TwistingNether",
},
{
["note"] = "Ayije",
["name"] = "Hotdogsuzy",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "TwistingNether",
},
{
["note"] = "Ayije",
["name"] = "Ayijexo",
["rank"] = "Raider",
["class"] = "SHAMAN",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Ayije",
["name"] = "Ayijeqt",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "TwistingNether",
},
{
["note"] = "Ayije",
["name"] = "Uwurawr",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "TwistingNether",
},
{
["note"] = "Ayije",
["name"] = "Ayijeqtx",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "TwistingNether",
},
{
["note"] = "Bigt",
["name"] = "Bigchai",
["rank"] = "Raider",
["class"] = "MONK",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Bigt",
["name"] = "Bigtrunk",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "TarrenMill",
},
{
["note"] = "Bigt",
["name"] = "Bigtilted",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Bigt",
["name"] = "Bigtje",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "TarrenMill",
},
{
["note"] = "Bigt",
["name"] = "Bigtaunt",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Bigt",
["name"] = "Bigtilter",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Birdwatcher",
["name"] = "Vízquel",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Birila",
["name"] = "Birilloqt",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Birila",
["name"] = "Tankarillo",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Bob",
["name"] = "Evilbob",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Cammura",
["name"] = "Ereli",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Cammura",
["name"] = "Kaiproof",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Silvermoon",
},
{
["note"] = "Cammura",
["name"] = "Cammura",
["rank"] = "Trial Raider",
["class"] = "MONK",
["rankIndex"] = 4,
["realm"] = "Silvermoon",
},
{
["note"] = "Cammura 4th char",
["name"] = "Joakes",
["rank"] = "Raider Alt",
["class"] = "ROGUE",
["rankIndex"] = 5,
["realm"] = "Silvermoon",
},
{
["note"] = "Completely useless.",
["name"] = "Tzicusoarâ",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crïms",
["rank"] = "Raider Alt",
["class"] = "WARLOCK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crimsp",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crímsq",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crimsv",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Críms",
["rank"] = "Raider",
["class"] = "MAGE",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crimsgood",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crimsmood",
["rank"] = "Raider Alt",
["class"] = "ROGUE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crimsf",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crimsfq",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crìms",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Crims",
["name"] = "Crimsu",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Dev",
["name"] = "Devbonks",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Dev",
["name"] = "Dévo",
["rank"] = "Raider",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Dev",
["name"] = "Devdunks",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Dsune",
["name"] = "Twosune",
["rank"] = "Officer Alt",
["class"] = "DRUID",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Dsune",
["name"] = "Dsune",
["rank"] = "Officer",
["class"] = "DRUID",
["rankIndex"] = 1,
["realm"] = "Draenor",
},
{
["note"] = "Dsune",
["name"] = "Fivesune",
["rank"] = "Officer Alt",
["class"] = "DRUID",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Dsune",
["name"] = "Threesune",
["rank"] = "Officer Alt",
["class"] = "DRUID",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Emil",
["name"] = "Forbandelser",
["rank"] = "Social",
["class"] = "WARLOCK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "FSH",
["name"] = "Mehs",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "GI",
["name"] = "Îgsem",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Shacow",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "BurningLegion",
},
{
["note"] = "Garo",
["name"] = "Garodh",
["rank"] = "Raider",
["class"] = "DEMONHUNTER",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Kurwadru",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Garolock",
["rank"] = "Raider Alt",
["class"] = "WARLOCK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Garowar",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Garohunt",
["rank"] = "Raider Alt",
["class"] = "HUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Fokfok",
["rank"] = "Raider Alt",
["class"] = "ROGUE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Garodk",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Garo",
["name"] = "Garussy",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Hovis",
["name"] = "Burntloaf",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Hovis",
["name"] = "Ryeloaf",
["rank"] = "Social",
["class"] = "WARLOCK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Igsem",
["name"] = "Smìle",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Igsem",
["name"] = "Solork",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Igsem",
["name"] = "Snufss",
["rank"] = "Social",
["class"] = "WARRIOR",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Igsem Alt",
["name"] = "Happyfeed",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "JB",
["name"] = "Jdotchi",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "TarrenMill",
},
{
["note"] = "JB",
["name"] = "Jdotb",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "JB",
["name"] = "Jdotblust",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "TarrenMill",
},
{
["note"] = "JB",
["name"] = "Jdotbop",
["rank"] = "Social",
["class"] = "PALADIN",
["rankIndex"] = 6,
["realm"] = "TarrenMill",
},
{
["note"] = "JB",
["name"] = "Jdotangel",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "TarrenMill",
},
{
["note"] = "JB",
["name"] = "Jdotbronze",
["rank"] = "Social",
["class"] = "EVOKER",
["rankIndex"] = 6,
["realm"] = "TarrenMill",
},
{
["note"] = "Joker",
["name"] = "Kìldèmand",
["rank"] = "Social",
["class"] = "WARLOCK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Joker",
["name"] = "Jòkér",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Joker",
["name"] = "Jôkêr",
["rank"] = "Social",
["class"] = "ROGUE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Jokers friend (Monster)",
["name"] = "Vizboom",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kaellach",
["name"] = "Caelah",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kaellach",
["name"] = "Kaelack",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kaellach",
["name"] = "Kaellak",
["rank"] = "Social",
["class"] = "ROGUE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kait",
["name"] = "Kaitiya",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Kait",
["name"] = "Kaitthree",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Kait",
["name"] = "Kaít",
["rank"] = "Raider",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Kaz",
["name"] = "Kazublind",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Kaz",
["name"] = "Kazushii",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Kaz",
["name"] = "Outscaled",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Kaz",
["name"] = "Kazuru",
["rank"] = "Trial Raider",
["class"] = "PRIEST",
["rankIndex"] = 4,
["realm"] = "Draenor",
},
{
["note"] = "Kaz",
["name"] = "Kazuruu",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Kaz",
["name"] = "Immerensis",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Keffalo",
["name"] = "Keffallo",
["rank"] = "Officer",
["class"] = "MAGE",
["rankIndex"] = 1,
["realm"] = "Draenor",
},
{
["note"] = "Kihu",
["name"] = "Kihublue",
["rank"] = "Social",
["class"] = "ROGUE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kihu",
["name"] = "Kihuboiler",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kihu",
["name"] = "Kihukms",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kihu",
["name"] = "Kihusizediff",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kihu",
["name"] = "Kihuws",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kihu",
["name"] = "Kihucumblast",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Kihu",
["name"] = "Kihumonkeyxd",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "Kazzak",
},
{
["note"] = "Koru",
["name"] = "Korudktwo",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Koru",
["name"] = "Korumo",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Koru",
["name"] = "Korupal",
["rank"] = "Raider",
["class"] = "PALADIN",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Koru",
["name"] = "Korulock",
["rank"] = "Raider Alt",
["class"] = "WARLOCK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Koru",
["name"] = "Korudk",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Koru",
["name"] = "Cowrumoo",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Koru",
["name"] = "Korudh",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Korupal",
["name"] = "Korusham",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "MS",
["name"] = "Nilius",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "MS",
["name"] = "Krazzix",
["rank"] = "Social",
["class"] = "WARRIOR",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "MS",
["name"] = "Nilvayn",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "MS",
["name"] = "Holeywoman",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "MS",
["name"] = "Vexìa",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "MS",
["name"] = "Zyxaes",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "MS",
["name"] = "Dragonwok",
["rank"] = "Social",
["class"] = "EVOKER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Marge",
["name"] = "Ilostmytotem",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Marge",
["name"] = "Ilostmytime",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Mikorra",
["name"] = "Mìkòrrà",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Mikorra(social)",
["name"] = "Nyamchi",
["rank"] = "Social",
["class"] = "MONK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragepriest",
["rank"] = "Officer Alt",
["class"] = "PRIEST",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Mìrage",
["rank"] = "Officer",
["class"] = "ROGUE",
["rankIndex"] = 1,
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragepal",
["rank"] = "Officer Alt",
["class"] = "PALADIN",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragethree",
["rank"] = "Officer Alt",
["class"] = "ROGUE",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragedruid",
["rank"] = "Officer Alt",
["class"] = "DRUID",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragedh",
["rank"] = "Officer Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Mirage",
["name"] = "Miragetwo",
["rank"] = "Officer Alt",
["class"] = "ROGUE",
["rankIndex"] = 2,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Nirana",
["rank"] = "Raider",
["class"] = "PRIEST",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Anuria",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Nirandra",
["rank"] = "Raider Alt",
["class"] = "ROGUE",
["rankIndex"] = 5,
["realm"] = "Antonidas",
},
{
["note"] = "Nirana",
["name"] = "Blinkaroo",
["rank"] = "Raider Alt",
["class"] = "MAGE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Zerwo",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Getmisty",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Tufrer",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Blackrock",
},
{
["note"] = "Nirana",
["name"] = "Tufrer",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Lundara",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Aegwynn",
},
{
["note"] = "Nirana",
["name"] = "Nialora",
["rank"] = "Raider Alt",
["class"] = "MAGE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Ranina",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nirana",
["name"] = "Zonira",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nish",
["name"] = "Nishaman",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nish",
["name"] = "Nishdr",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Nish",
["name"] = "Nishevoker",
["rank"] = "Raider",
["class"] = "EVOKER",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Pricey",
["name"] = "Pricéyy",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Pricey",
["name"] = "Prîceyy",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairwl",
["rank"] = "Raider Alt",
["class"] = "WARLOCK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairw",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairm",
["rank"] = "Raider",
["class"] = "MONK",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairdk",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairboom",
["rank"] = "Raider",
["class"] = "DRUID",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairxd",
["rank"] = "Raider Alt",
["class"] = "HUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Replair",
["name"] = "Replairpr",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Retired",
["name"] = "Durexkael",
["rank"] = "Social",
["class"] = "WARRIOR",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Retired",
["name"] = "Sponksgrip",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "TarrenMill",
},
{
["note"] = "Retired Bob (?)",
["name"] = "Morningbob",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Santhe",
["name"] = "Sån",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Santhe",
["name"] = "Sãn",
["rank"] = "Social",
["class"] = "WARLOCK",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Santhe",
["name"] = "Sánthyr",
["rank"] = "Social",
["class"] = "EVOKER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Scrapps",
["name"] = "Scrapps",
["rank"] = "Trial Raider",
["class"] = "HUNTER",
["rankIndex"] = 4,
["realm"] = "Stormscale",
},
{
["note"] = "Scrapps",
["name"] = "Scraps",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Stormscale",
},
{
["note"] = "Scrapps",
["name"] = "Scrappz",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "Stormscale",
},
{
["note"] = "Scrapps",
["name"] = "Scrapp",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Stormscale",
},
{
["note"] = "Scrapps",
["name"] = "Scrappd",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Stormscale",
},
{
["note"] = "Seb",
["name"] = "Szb",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Seb",
["name"] = "Sezb",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Seb",
["name"] = "Soomb",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Seb",
["name"] = "Sepb",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Seb",
["name"] = "Sbe",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Seb",
["name"] = "Sesb",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "TarrenMill",
},
{
["note"] = "Seb",
["name"] = "Sedb",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Self proclaimed funny guy.",
["name"] = "Igsëm",
["rank"] = "Social",
["class"] = "EVOKER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Shade",
["name"] = "Shadewl",
["rank"] = "Raider",
["class"] = "WARLOCK",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Shade",
["name"] = "Shadeqtxd",
["rank"] = "Raider Alt",
["class"] = "WARLOCK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Shade",
["name"] = "Shadeto",
["rank"] = "Raider Alt",
["class"] = "WARLOCK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Sharp",
["name"] = "Belzo",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Sly",
["name"] = "Slyxhthree",
["rank"] = "Raider Alt",
["class"] = "MAGE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Sly",
["name"] = "Slyxhtwo",
["rank"] = "Raider Alt",
["class"] = "MAGE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Sly",
["name"] = "Slyxhfour",
["rank"] = "Raider Alt",
["class"] = "MAGE",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Sly",
["name"] = "Slyxhamstrez",
["rank"] = "Raider",
["class"] = "MAGE",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Smuts SP",
["name"] = "Plipa",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Sofles",
["name"] = "Soflesw",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Blackrock",
},
{
["note"] = "Sofles",
["name"] = "Soflesp",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Blackrock",
},
{
["note"] = "Sofles",
["name"] = "Soflesm",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Sofles",
["name"] = "Soflesxo",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Sofles",
["name"] = "Sofles",
["rank"] = "Trial Raider",
["class"] = "DEMONHUNTER",
["rankIndex"] = 4,
["realm"] = "Draenor",
},
{
["note"] = "Sonag",
["name"] = "Soneq",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Sonag",
["name"] = "Sonac",
["rank"] = "Social",
["class"] = "DRUID",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Sonag",
["name"] = "Sonuc",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Sonag",
["name"] = "Sonag",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Sonag",
["name"] = "Sokaya",
["rank"] = "Social",
["class"] = "ROGUE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Sonag",
["name"] = "Sonug",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Spurs / Morocco Fan or somethin",
["name"] = "Sleetpriest",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Swatty",
["name"] = "Swatt",
["rank"] = "Raider",
["class"] = "WARRIOR",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Swatty",
["name"] = "Swatt",
["rank"] = "Raider Alt",
["class"] = "HUNTER",
["rankIndex"] = 5,
["realm"] = "Stormscale",
},
{
["note"] = "Swatty",
["name"] = "Swatteh",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Swatty",
["name"] = "Swatty",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "DieAldor",
},
{
["note"] = "Swatty",
["name"] = "Swattywoyer",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Swatty",
["name"] = "Swatty",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Swatty",
["name"] = "Swattpally",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Swatty",
["name"] = "Swátt",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "BronzeDragonflight",
},
{
["note"] = "Swatty",
["name"] = "Dragondsnutz",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Teew",
["name"] = "Femaleirl",
["rank"] = "Raider Alt",
["class"] = "WARRIOR",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Teew",
["name"] = "Teew",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "The real BROWNIE!",
["name"] = "Lostbrownie",
["rank"] = "Social",
["class"] = "SHAMAN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Tiwar",
["name"] = "Rekiya",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Folyr",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Unlovedvaras",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Varasdruid",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Varas",
["name"] = "Váras",
["rank"] = "Raider",
["class"] = "ROGUE",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "WHY IS YOUR PP SO SMALL",
["name"] = "Igsém",
["rank"] = "Social",
["class"] = "PRIEST",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "Worst",
["name"] = "Xddshock",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Ravencrest",
},
{
["note"] = "Worst",
["name"] = "Botoa",
["rank"] = "Raider Alt",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 5,
["realm"] = "TwistingNether",
},
{
["note"] = "Worst",
["name"] = "Worstxd",
["rank"] = "Trial Raider",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 4,
["realm"] = "Ravencrest",
},
{
["note"] = "Wort",
["name"] = "Whort",
["rank"] = "Raider Alt",
["class"] = "HUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Dogmaxxing",
["rank"] = "Raider Alt",
["class"] = "HUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Wort",
["name"] = "Wortxd",
["rank"] = "Raider",
["class"] = "HUNTER",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zaraine",
["rank"] = "Raider",
["class"] = "PALADIN",
["rankIndex"] = 3,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarastwo",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Nerfmønks",
["rank"] = "Raider Alt",
["class"] = "MONK",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarainep",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarainedh",
["rank"] = "Raider Alt",
["class"] = "DEMONHUNTER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazafive",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarasthree",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zarainedudu",
["rank"] = "Raider Alt",
["class"] = "DRUID",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zaraines",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazafour",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazaseven",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Turbogrief",
["rank"] = "Raider Alt",
["class"] = "EVOKER",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazapriest",
["rank"] = "Raider Alt",
["class"] = "PRIEST",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazathree",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zara",
["name"] = "Zazasix",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zaraine",
["name"] = "Zazaeight",
["rank"] = "Raider Alt",
["class"] = "PALADIN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "Zaraine",
["name"] = "Zarasfive",
["rank"] = "Raider Alt",
["class"] = "SHAMAN",
["rankIndex"] = 5,
["realm"] = "Draenor",
},
{
["note"] = "average vision of nzoth enjoyer",
["name"] = "Eksl",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "does 100k overall on fire",
["name"] = "Mønstër",
["rank"] = "Social",
["class"] = "MAGE",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "glitchgang alt",
["name"] = "Hmstrcombat",
["rank"] = "Social",
["class"] = "PALADIN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "vizquel/monster",
["name"] = "Import",
["rank"] = "Social",
["class"] = "HUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "washed up social",
["name"] = "Míkórrá",
["rank"] = "Social",
["class"] = "PALADIN",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "weeeeeeeee",
["name"] = "Abrelshud",
["rank"] = "Social",
["class"] = "DEATHKNIGHT",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
{
["note"] = "yo",
["name"] = "Skalicious",
["rank"] = "Social",
["class"] = "DEMONHUNTER",
["rankIndex"] = 6,
["realm"] = "Draenor",
},
},
["guildName"] = "Evolve",
}
